### ISSUE TITLE
Ember Site New Issues

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#510]
## Pending Tasks
- [ ] Error messages on Step 1, 2, 3 in Join Section Form
- [ ] Render join data for Super user on the page same as Step 4
- [ ] Toast message API errors and success
- [ ] Add number of Hours field

**Comment by rohan09-raj** [comment]
## Task 1 - Image Reference
![image](https://github.com/Real-Dev-Squad/website-www/assets/78433013/eb6c6f90-8b8e-4332-bf33-a18d27d97507)

**Comment by rohan09-raj** [comment]
## Task 4 - Image Reference
![image](https://github.com/Real-Dev-Squad/website-www/assets/78433013/b6fddef3-a9d0-475c-8e59-4a4c979a076d)
