### ISSUE TITLE
Add meta tags for good previews

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-www#68]
Currently, the Preview of the Landing Page is not very good. We need to add meta tags to make it better previewed when we share the links of RealDevSquad.
- [x] Add meta tags for Twitter
- [x] Add meta tags for Facebook
- [x] Add meta tags for Discord
- [x] Add meta tags for Linkedin
- [x] Add meta tags for Google

Use this image for the meta tags 
![RealDevSquadLogoSEO](https://user-images.githubusercontent.com/78433013/148638139-3ab33ddd-1fd1-4ced-b1f9-e9ed104300ed.png)

Use this description for description meta tags
`Community of developers who collaborate to build Real software.`

Resources :
(Use these sites to generate meta tags)
https://metatags.io/
https://www.opengraph.xyz/

**Comment by priyanshk20** [comment]
I want to take up this task.
