### ISSUE TITLE
[Onboarding Flow] - Profile Service Link Verification Page

### ISSUE THREAD

**Issue by shubhamsigdar1** [Real-Dev-Squad/website-www#730]
# [Onboarding Flow] - Profile Service Link Verification Page

## Overview:

A page that displays the response from the Identity Service. The page should indicate whether my request is pending, verified, or blocked.

## User Stories:

- As a user in the onboarding flow, I should be directed to the "Profile Service Link Verification Page" after completing the profile linking process.
- As a user, The page should clearly show if my request is pending, verified, or blocked.
- As a user, On the "Profile Service Link Verification Page," I should see a clear indication of the response from the Identity Service.
- As a user, If profileStatus is "pending," then I see reload button which reload the page
- As a user, If profileStatus is "blocked" then I see next button which take me to the chaincode page.
- As a user, If profileStatus is "verified" then I see next button which take me to the discord link page.

## Requirement:

**Design Doc** https://docs.google.com/document/d/1ra6Nagmfbywhc8-_fRtmv1K688uDwqLQTOH-Om2t7oE/edit?usp=sharing

**Wireframe:** https://excalidraw.com/#json=YTa926cvq2ii71x1o74JV,s1pCCLxvb5OCb-EEL45bIQ

![image](https://github.com/Real-Dev-Squad/website-www/assets/107163260/906956de-9f11-4dd3-bb95-54db414ecaad)

## Acceptance Criteria:

- [ ] TDD
- [ ] Upon successful completion of the profile linking process in the onboarding flow, the user should be automatically directed to the "Profile Service Link Verification Page."
- [ ] The "Profile Service Link Verification Page" should prominently display the user's profileStatus (pending, verified, or blocked).
- [ ] If the profileStatus is "pending," the page should include a "Reload" button, which allows the user to refresh or reload the page to check for updates.
- [ ] If the profileStatus is "blocked," the page should include a "Next" button that, when clicked, directs the user to the "Chaincode Page."
- [ ] If the profileStatus is "verified," the page should include a "Next" button that, when clicked, directs the user to the "Discord Link Page."
- [ ] Under feature flag

## Subtasks:

- https://github.com/Real-Dev-Squad/website-www/issues/731
- https://github.com/Real-Dev-Squad/website-www/issues/732
- https://github.com/Real-Dev-Squad/website-www/issues/733
